# Generated by Django 5.0.7 on 2024-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_joke_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='answer',
            field=models.TextField(max_length=100),
        ),
    ]
